import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {client} from '../lib/client'
import { PageData } from '@/interface'
import Hero from '@/components/Hero'
import Experience from '@/components/Experience'

const inter = Inter({ subsets: ['latin'] })

export default function Home({pages,experiences}: {pages: PageData[],experiences: any[]}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero data={pages.find((item)=>item.title==="Hero")}/>
        <Experience data={experiences}/>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const pages = await client.fetch(`*[_type == "page"]`)
  const experiences = await client.fetch(`*[_type == "experience"]`)
  console.log(experiences)
  return {
    props: {
      pages,
      experiences
    }
}
}
